                                  ""
 ""                                 "level" "Overall"   
  "n"                               ""      "25"        
  "UPLUG_F (%)"                     "1"     "21 (84.0) "
  ""                                NA      " 4 (16.0) "
  "UPLUG_UTILIS (%)"                "0"     " 2 ( 8.0) "
  ""                                "1"     "19 (76.0) "
  ""                                NA      " 4 (16.0) "
  "UPLUG_UTILIS_TPS (%)"            "0"     " 1 ( 4.0) "
  ""                                "0000"  " 1 ( 4.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DEFECT (%)"                "0"     "17 (68.0) "
  ""                                "1"     " 4 (16.0) "
  ""                                NA      " 4 (16.0) "
  "UPLUG_DEFECT_PORT (%)"           "0"     " 1 ( 4.0) "
  ""                                "1"     " 3 (12.0) "
  ""                                NA      "21 (84.0) "
  "UPLUG_DEFECT_CONNECT (%)"        "0"     " 1 ( 4.0) "
  ""                                "1"     " 3 (12.0) "
  ""                                NA      "21 (84.0) "
  "UPLUG_DEFECT_REMPL_PORT (%)"     "0"     " 3 (12.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "21 (84.0) "
  "UPLUG_DEFECT_REMPL_CONNECT (%)"  "0"     " 3 (12.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "21 (84.0) "
  "UPLUG_DEFECT_ARRET (%)"          "0"     " 2 ( 8.0) "
  ""                                "1"     " 2 ( 8.0) "
  ""                                NA      "21 (84.0) "
  "UPLUG_DIFF (%)"                  "0"     "21 (84.0) "
  ""                                NA      " 4 (16.0) "
  "UPLUG_F1 (%)"                    "1"     "20 (80.0) "
  ""                                NA      " 5 (20.0) "
  "UPLUG_UTILIS1 (%)"               "0"     " 1 ( 4.0) "
  ""                                "1"     "19 (76.0) "
  ""                                NA      " 5 (20.0) "
  "UPLUG_UTILIS_TPS1 (%)"           "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT1 (%)"               "0"     "17 (68.0) "
  ""                                "1"     " 3 (12.0) "
  ""                                NA      " 5 (20.0) "
  "UPLUG_DEFECT_PORT1 (%)"          "1"     " 3 (12.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_DEFECT_CONNECT1 (%)"       "0"     " 2 ( 8.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_DEFECT_REMPL_PORT1 (%)"    "0"     " 1 ( 4.0) "
  ""                                "1"     " 2 ( 8.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_DEFECT_REMPL_CONNECT1 (%)" "0"     " 2 ( 8.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_DEFECT_ARRET1 (%)"         "0"     " 2 ( 8.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_DIFF1 (%)"                 "0"     "20 (80.0) "
  ""                                NA      " 5 (20.0) "
  "UPLUG_F2 (%)"                    "1"     "13 (52.0) "
  ""                                NA      "12 (48.0) "
  "UPLUG_UTILIS2 (%)"               "1"     "13 (52.0) "
  ""                                NA      "12 (48.0) "
  "UPLUG_DEFECT2 (%)"               "0"     "12 (48.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "12 (48.0) "
  "UPLUG_DEFECT_PORT2 (%)"          "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_CONNECT2 (%)"       "1"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_REMPL_PORT2 (%)"    "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_REMPL_CONNECT2 (%)" "1"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_ARRET2 (%)"         "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DIFF2 (%)"                 "0"     "13 (52.0) "
  ""                                NA      "12 (48.0) "
  "UPLUG_F3 (%)"                    "1"     "17 (68.0) "
  ""                                NA      " 8 (32.0) "
  "UPLUG_UTILIS3 (%)"               "1"     "17 (68.0) "
  ""                                NA      " 8 (32.0) "
  "UPLUG_DEFECT3 (%)"               "0"     "17 (68.0) "
  ""                                NA      " 8 (32.0) "
  "UPLUG_DIFF3 (%)"                 "0"     "13 (52.0) "
  ""                                "1"     " 4 (16.0) "
  ""                                NA      " 8 (32.0) "
  "UPLUG_DIFF_REMPL_PORT3 (%)"      "0"     " 4 (16.0) "
  ""                                NA      "21 (84.0) "
  "UPLUG_DIFF_REMPL_CONNECT3 (%)"   "0"     " 3 (12.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "21 (84.0) "
  "UPLUG_F4 (%)"                    "1"     "17 (68.0) "
  ""                                NA      " 8 (32.0) "
  "UPLUG_UTILIS4 (%)"               "0"     " 1 ( 4.0) "
  ""                                "1"     "16 (64.0) "
  ""                                NA      " 8 (32.0) "
  "UPLUG_UTILIS_TPS4 (%)"           "0007"  " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT4 (%)"               "0"     "15 (60.0) "
  ""                                "1"     " 2 ( 8.0) "
  ""                                NA      " 8 (32.0) "
  "UPLUG_DEFECT_PORT4 (%)"          "0"     " 1 ( 4.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DEFECT_CONNECT4 (%)"       "1"     " 2 ( 8.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DEFECT_REMPL_PORT4 (%)"    "0"     " 2 ( 8.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DEFECT_REMPL_CONNECT4 (%)" "0"     " 1 ( 4.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DEFECT_ARRET4 (%)"         "0"     " 1 ( 4.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DIFF4 (%)"                 "0"     "16 (64.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      " 8 (32.0) "
  "UPLUG_DIFF_REMPL_PORT4 (%)"      "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DIFF_REMPL_CONNECT4 (%)"   "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_F5 (%)"                    "1"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_UTILIS5 (%)"               "1"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_DEFECT5 (%)"               "0"     "10 (40.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_DEFECT_PORT5 (%)"          "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_CONNECT5 (%)"       "1"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_REMPL_PORT5 (%)"    "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_REMPL_CONNECT5 (%)" "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_ARRET5 (%)"         "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DIFF5 (%)"                 "0"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_F6 (%)"                    "1"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_UTILIS6 (%)"               "1"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DEFECT6 (%)"               "0"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DIFF6 (%)"                 "0"     "11 (44.0) "
  ""                                "1"     " 3 (12.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DIFF_REMPL_PORT6 (%)"      "0"     " 3 (12.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_DIFF_REMPL_CONNECT6 (%)"   "0"     " 1 ( 4.0) "
  ""                                "1"     " 2 ( 8.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_F7 (%)"                    "1"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_UTILIS7 (%)"               "1"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DEFECT7 (%)"               "0"     "13 (52.0) "
  ""                                "1"     " 1 ( 4.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DEFECT_PORT7 (%)"          "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_CONNECT7 (%)"       "1"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_REMPL_PORT7 (%)"    "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_REMPL_CONNECT7 (%)" "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DEFECT_ARRET7 (%)"         "0"     " 1 ( 4.0) "
  ""                                NA      "24 (96.0) "
  "UPLUG_DIFF7 (%)"                 "0"     "11 (44.0) "
  ""                                "1"     " 3 (12.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DIFF_REMPL_PORT7 (%)"      "0"     " 3 (12.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_DIFF_REMPL_CONNECT7 (%)"   "0"     " 3 (12.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_F8 (%)"                    "1"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_UTILIS8 (%)"               "1"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_DEFECT8 (%)"               "0"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_DIFF8 (%)"                 "0"     " 9 (36.0) "
  ""                                "1"     " 2 ( 8.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_DIFF_REMPL_PORT8 (%)"      "0"     " 2 ( 8.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DIFF_REMPL_CONNECT8 (%)"   "0"     " 2 ( 8.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_F9 (%)"                    "1"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_UTILIS9 (%)"               "1"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DEFECT9 (%)"               "0"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DIFF9 (%)"                 "0"     "11 (44.0) "
  ""                                "1"     " 3 (12.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DIFF_REMPL_PORT9 (%)"      "0"     " 3 (12.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_DIFF_REMPL_CONNECT9 (%)"   "0"     " 3 (12.0) "
  ""                                NA      "22 (88.0) "
  "UPLUG_F10 (%)"                   "1"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_UTILIS10 (%)"              "1"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DEFECT10 (%)"              "0"     "14 (56.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DIFF10 (%)"                "0"     "12 (48.0) "
  ""                                "1"     " 2 ( 8.0) "
  ""                                NA      "11 (44.0) "
  "UPLUG_DIFF_REMPL_PORT10 (%)"     "0"     " 2 ( 8.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DIFF_REMPL_CONNECT10 (%)"  "0"     " 2 ( 8.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_F11 (%)"                   "1"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_UTILIS11 (%)"              "1"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_DEFECT11 (%)"              "0"     "11 (44.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_DIFF11 (%)"                "0"     " 9 (36.0) "
  ""                                "1"     " 2 ( 8.0) "
  ""                                NA      "14 (56.0) "
  "UPLUG_DIFF_REMPL_PORT11 (%)"     "0"     " 2 ( 8.0) "
  ""                                NA      "23 (92.0) "
  "UPLUG_DIFF_REMPL_CONNECT11 (%)"  "0"     " 2 ( 8.0) "
  ""                                NA      "23 (92.0) "
